name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install XcodeGen
        run: brew install xcodegen
      - name: Generate Xcode project
        run: xcodegen generate
      - name: Show Xcode version
        run: xcodebuild -version | cat
      - name: Build and test
        run: xcodebuild -scheme LeafLens -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -sdk iphonesimulator -enableCodeCoverage YES clean test | xcpretty
        env:
          NSUnbufferedIO: YES